# All parameters can be overwritten with environment variables, which names match
# parameter name with "MIX" prefix. For example, to change "Application.Addr" use
# MIX_APPLICATION_ADDR environment variable.

[Application]
Env = "production"
Addr = ":8000"
LogLevel = "info"
Secret = "CG5wJ3WvPgeMEHixpIkXtFslmNQAuyOj"
BucketPath = "public/media"

[Database]
Host = "127.0.0.1"
Port = 6432 # PgBouncer port
User = "postgres"
Password = "secret"
MigrationsDir = "db/migrate"
MigrationsTable = "schema_migrations"
